### ISSUE TITLE
TQC does not accept the Vault Path

### ISSUE THREAD

**Issue by HerrUntermoser** [Malgardian/TQCollector#30] opened 2022-10-22 09:58 UTC
i can't change the "Standard" Vault path, because TQC doesn't accept the new ones. My TQV Version is 4.3.x

**Comment by Malgardian** [comment] 2022-10-22 21:04
Where's your actual Vault path located?

**Comment by HerrUntermoser** [comment] 2022-10-23 09:33
C:\Users\Username\Documents\My Games\TQVault_AE

**Comment by HerrUntermoser** [comment] 2022-10-26 10:43
The Vault Files. ;)

**Comment by Malgardian** [comment] 2022-10-29 18:43
Alright, I can't reproduce this on my end at all. Can you please make a screenshot of the following things:
- TQC window with the path selection
- windows explorer window of your vault directory.

**Comment by HerrUntermoser** [comment] 2022-10-30 16:41
![TQC_shot1](https://user-images.githubusercontent.com/35288770/198890477-9ab8b812-e463-4cfc-a4f4-bac3382ed0c7.jpg)
![TQC_shot2](https://user-images.githubusercontent.com/35288770/198890495-ec92c328-9a85-44b0-a56c-0d060d0b931b.jpg)

**Comment by Malgardian** [comment] 2022-10-31 14:05
Should be fixed with TQC 1.4.0.1 which I just published. Let me know if there still an issue.

**Closed by Malgardian** 2022-10-31 14:05 UTC
